# ─── Server ────────────────────────────────────────────────────────────────
server.port=8082

# ─── Database ──────────────────────────────────────────────────────────────
spring.datasource.url=${DATABASE_URL:jdbc:postgresql://localhost:5435/product_db}
spring.datasource.username=${DATABASE_USER:postgres}
spring.datasource.password=${DATABASE_PASSWORD:postgres}
spring.datasource.driver-class-name=org.postgresql.Driver
